DROP SCHEMA IF EXISTS dbLocations;
CREATE SCHEMA IF NOT EXISTS dbLocations;
CREATE TABLE IF NOT EXISTS dbLocations.Location (
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL,
  dateT DATETIME NOT NULL,
  PRIMARY KEY(id)
);
INSERT INTO dbLocations.Location(latitude, longitude, dateT)
VALUES('20.30303', '15.03040','9999-12-31 23:59:59');

